import { Product } from "./types/Product";
export const sampleProducts: Product[] = [
  {
    name: "Nike Slim Shirt",
    slug: "nike-slim-shirt",
    category: "Shirts",
    image: "",
    price: 120,
    countIsStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    description: "high quality shirt",
  },
  {
    name: "Nike Slim Shirt",
    slug: "nike-slim-shirt",
    category: "Shirts",
    image: "",
    price: 120,
    countIsStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    description: "high quality shirt",
  },
  {
    name: "Nike Slim Shirt",
    slug: "nike-slim-shirt",
    category: "Pants",
    image: "",
    price: 120,
    countIsStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    description: "high quality shirt",
  },
];
